### ISSUE TITLE
new colors from Perler

### ISSUE THREAD

**Issue by SteelSkyStudios** [maxcleme/beadifier#105]
First off wanna say thank you for having "Beadifier" up as a usable sight. i use it alot! so thank you very much. Second
Perler Beads just put out 3 new colors

Peacock
Rich Butter
Brick

Thanx again!

**Comment by maxcleme** [comment]
Hey, thanks for the kind comment!

Do you happen to have the new color's code? In RGB or something?

**Comment by SteelSkyStudios** [comment]
Sorry I'm a potato...not in my skill set. 😭

**Comment by instaloadererror** [comment]
Thanks for the site, it's amazing how good it is at converting images that aren't already pixel art.

> Sadly it won't really help as we need to encode those value in the app 😅

This site (https://toptierbeads.com/pages/top-tier-and-perler-color-chart-and-comparisons) has RGB values for Perler and Artkal colors. 

Rich Butter: 246, 202, 105

Brick: 252, 149, 116

Peacock: 0, 144, 172

I also had two suggestions for features. I have no idea if these are simple things to add or not so forgive me if I'm suggesting the impossible for you.

1) Allow for more customization of pattern size. There's two ways I think this would be useful. One would be to allow for selecting exact sizes (say 30x40 beads). The second would be doing it by percentage of the original image size. This second one would be particularly useful when converting non-pixel art images as it would sidestep the need to fiddle with ratios of board lengths and allow for the user to just resize it to 60% say. 

2) Give the option to use consecutive numbers instead of symbols when making the pattern. Personally I just find it easier to keep track of things when the colors are numbered 1-10 rather than the generated symbols.

**Comment by maxcleme** [comment]
Thanks for the color codes! I'm adding the new references, it should be available in `beadifier` soonish.

Regarding the two other feature requests, I would suggest to open separated issues at https://github.com/maxcleme/beadifier/issues instead. 

However I'll be honest and share that this project is kind of in maintenance mode, and I doubt I'll add new features soon.

**Comment by SteelSkyStudios** [comment]
Amazing thank you and the others for updates and help! Great people!
