### ISSUE TITLE
Exporting the pattern.

### ISSUE THREAD

**Issue by negrojombo** [maxcleme/beadifier#24]
Option to export it as a image. Also giving "style" options.
![20200420_075539](https://user-images.githubusercontent.com/64017980/79754055-855b7180-82dc-11ea-9e94-e81291af2b94.jpg)

**Comment by maxcleme** [comment]
Hi, thanks for feedback however I don't get it, could you be more specific about?

**Comment by negrojombo** [comment]
When exporting the pattern as a png or jpg, it would have the color codes. It would be easier for others who are confused with pdf files. It would look something like this:
![beadified_image-1](https://user-images.githubusercontent.com/64017980/79756477-47f8e300-82e0-11ea-967d-1716d3c422a6.png)

**Comment by maxcleme** [comment]
To be honest I used PDF for two main features :
+ Multiple pages
+ Vectorized drawing in order to allow user to zoom as much as they want to see each bead's color reference. 

Generating only one image made from all boards could be done, however it would have to either : 
+ Be vectorized as well (resulting in a SVG file, which IMO would also confused people of PDF are already confusing)
+ Having a ridiculous amount of pixel for huge pattern (and/or mini), making the file oversized.

I need to make some experiment about the image size in very high resolution.

Did I understand your point?

**Comment by negrojombo** [comment]
Yes, you did. Another option is to have the pattern seperated into four different pictures.

**Comment by maxcleme** [comment]
If the pattern is divided into N parts, what's the difference with the pdf then?

**Comment by negrojombo** [comment]
Speaking for myself there wouldn't be a difference. However on an android/iPhone a seperate app may be needed. Having the "option" to export it differently is nice.

**Comment by maxcleme** [comment]
Thing is, this is a website and browser support pdf since long time now, I always create/view my pattern from my Android phone myself 😅

But you're absolutely right for resuming an ongoing project, I need my file explorer to retrieve the pdf instead of using gallery, you got the point here :+1:

**Comment by maxcleme** [comment]
@negrojombo 

I played a little with image export, I ended up with something like this : 

![download (2)](https://user-images.githubusercontent.com/7669401/80199865-148cc000-8622-11ea-81a6-9016586a3bad.png)

I still need to look at : 
+ Inventory section
+ Bench image size results depending of the number of boards
+ Look at SVG
+ Make color references more readable depending on the background color

What are you thoughts about it ?

**Comment by negrojombo** [comment]
I think it's great. You outlined the boards dimensions and the color codes are easy to read.
Some may not prefer the pattern in the middle of the boards like the image above.. unless this is just an example.
Don't know if it would be easier for you to have one image file or seperate.. either is fine with me.

**Comment by maxcleme** [comment]
I still think color code readibility needs be greatly improved. 

Regarding the pattern being in the middle of boards it's links to a setting which is set by default, but it can be turned off if you want (advanced tab).

Generate one image per board can also be a something doable, but I guess downloading a zip file instead will leads to same issue as for PDF. 

Downloading N images could be really frustrating in case of big pattern (I usually do 3x4 boards pattern, having to download 12 images is more painful than opening a PDF with file explorer instead of gallery IMO)

**Comment by negrojombo** [comment]
One image is the easiest, but the file size may be the issue if it's a big pattern. Multiple images could work, instead of having an image per board. It could be seperated into a certain amount images ignoring the size of the actual pattern.

**Comment by maxcleme** [comment]
IMO splitting one board into 2 or more images would be a real pain to use 😅

**Comment by negrojombo** [comment]
Yeah it would. So one image and better readability for the color codes

**Comment by maxcleme** [comment]
Going to make further experiment next week, I'll keep you in touch

**Comment by maxcleme** [comment]
@negrojombo , still working on it but I started working again (professionally speaking) so I got less free time that previous weeks, but this feature is still planned, don't worry.

**Comment by jaymeh** [comment]
@maxcleme I hope you guys don't mind me weighing in here, I've actually been working on a tool very similar to beadifier. I couldn't find anything at the time of looking that allowed me to use an updated list of Artkal C Mini beads. I stumbled across this project on Reddit though and it seems like I might be able to use it instead of continuing my own.

An idea I had for the exports of the tool I've been working on is associating each colour with a symbol and displaying a key. I haven't fully worked out how it would work across multiple boards but I've attached an example of the export to PDF functionality I did as part of my project to demonstrate a potential alternative. Not sure if this helps or is a valid suggestion at this point in time but felt like I could weigh in.

[squirtle-pattern.pdf](https://github.com/maxcleme/beadifier/files/4789451/squirtle-pattern.pdf)

I think PDF is a good option, I'm pretty old school and print stuff off since it means I don't have to deal with screen dimming or notification distractions while I am beading so PDF seems a good way to go for me still.

Great tool though @maxcleme, I'm looking forward to seeing it improve in the future! :+1:

**Comment by maxcleme** [comment]
@jaymeh 

First, sorry for delay of the initial feature, still working from home since beginning of national lock-down, no free lunch breaks to work with project (I prefer spending time my family during lunch breaks / WE  :smile: )

> An idea I had for the exports of the tool I've been working on is associating each colour with a symbol and displaying a key.

I have to say that the mockup you created is really self explanatory ! Well done! I really like this idea of using symbol with are more easy to recognize. 

> I haven't fully worked out how it would work across multiple boards

If you are OK with PDF, the current PDF strategy create one board per page, might work as well for you.

IMO Few questions remain in order to be something viable and integrated.

+ How should we handle the symbol translation/dictionary, and how many different symbols could be potentially used ? Does this features should be restricted for pattern with less than N colors ? Since you can now select multiple brand when beading, the number of total colors can be really big.
+ How can I guarantee that color-to-symbol translation is reliable in time ? If a made two patterns with two sets of colors A and B, the intersection of these sets should have the same symbol across both patterns (eg: with time I could learn that Heart symbol is always C38). Meaning we need a way to dynamically translate color references to symbols (in order to work with new color coming from [here](https://github.com/maxcleme/beadcolors)), without duplicate.

Any thoughts ?

**Comment by jaymeh** [comment]
@maxcleme 

No need to apologise, I really respect that! As a developer with a young family also, I completely understand where you are coming from. I only have an hour or two each evening to either wind down or work on personal projects.

Thanks! I've made a few patterns using the generator method above and I have to say, you do remember that x symbol belongs to y colour as you are working on it.

Yeah, one pattern per page is working for me however I'm new to beading and don't have a large collection of them so I'm only ever working with smaller patterns (2x2 maximum).

> How should we handle the symbol translation/dictionary, and how many different symbols could be potentially used ? Does this features should be restricted for pattern with less than N colors ? Since you can now select multiple brand when beading, the number of total colors can be really big.

So I guess the symbols are limited to how many different ASCII characters you can use. For my app I created an array of different symbols (around 40) and assign a random symbol to a colour each time (they aren't tied to a specific colour). The symbols themselves aren't associated to the colour and sit separately but are attached to a colour and removed from the list as they used during the export of the PDF. Hope this makes sense :). 

>Does this features should be restricted for pattern with less than N colors ?

That's a good question A restriction might need to be added. My app only currently deals with Artkal Mini C and I hadn't fully thought about how I can support mixing different brands.

>How can I guarantee that color-to-symbol translation is reliable in time ? If a made two patterns with two sets of colors A and B, the intersection of these sets should have the same symbol across both patterns (eg: with time I could learn that Heart symbol is always C38). Meaning we need a way to dynamically translate color references to symbols (in order to work with new color coming from here), without duplicate.

So because I thought of making colour association dynamic you only ever need as many symbols as you have colours in your piece. I'm not really sure how complex/many different colours get used on sheets for different people (suppose it could be hundreds in theory). 

I also thought about have a different key per board. So for board 0-0 you have a key with only the colours used on it. With images spanning multiple board though, that might get confusing as the same symbol might be mapped to a different colour on a different board.

**Comment by maxcleme** [comment]
> I also thought about having a different key per board. So for board 0-0 you have a key with only the colours used on it. With images spanning multiple board though, that might get confusing as the same symbol might be mapped to a different colour on a different board.

That was exactly my point, IMO that the thing to find out first if we want to integrate this feature. Having symbol changing from pattern to pattern of even from page to page would without a doubt be too confusing for end user.

Moreover, having a reliable/consistent translation between colors and symbols could lift up the limitation of number of colors. If you look at [FontAwesome](https://fontawesome.com/icons?d=gallery), there is like 7000+ different icons, so I guess we should be fine (we could also add style combination, eg:bold/italic/underline).

**Comment by jaymeh** [comment]
I have to agree, I think it would be confusing.

Ha, good point. I didn't think about using FontAwesome, that would make it a non issue so I think each colour should have it's own unique icon.

If you need me to try and pick anything up for this project be it some parts of this issue or any of the others, let me know. I'd love to get involved and help to progress beadifier further. 

I'm pretty new to angular and typescript (only used it for a side project lasting 2 - 3 months) so there might be some back and forth on PR's but happy to help wherever I can!

**Comment by maxcleme** [comment]
Thanks for proposing help for this project, really appreciated it !

May I ask you first to create an issue related to symbol translation ? I think we diverge from the original issue which was only image export instead of PDF (should be done soon, at least I hope). 

Using symbols instead of color names could be use in all type of export and IMO should be seen as higher-lever feature instead of just an export file type. Something that could be toggle in the `Advanced` tab maybe.

Let's going down further in the upcoming issue :)

**Comment by maxcleme** [comment]
@negrojombo 

Hey, sorry be being so late to this, but I actually implemented new export type (svg,png and jpg).

It should be available during the day (CI is running) on the website, please feel free to try it out for additional feedbacks !

I labeled them as "Beta" in order to gather multiple feedbacks before GA.

You might also encounter cache issue before seeing the new "export" tab.

Cheers!

**Comment by maxcleme** [comment]
Closing due to stale.
