### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by sunshin89** [maxcleme/beadifier#26]
Not sure how to title this. I’m not liking the new set up. Every time I change how many boards, the image disappears and I can’t tell what it looks like and if it’s how I want it.

**Comment by maxcleme** [comment]
That's pretty weird, this is obviously not the expected behavior. Mind to
share on which platform/browser the issue occurred? Did you try from other
platform/browser to see if it's global or more a compatibility issue? I
used it yesterday for personal project and everything worked well.

Correct me if I'm wrong, just to be sure I'm understanding well : When you
load an image, everything works fine for default 2x2 boards, but when you
go to board tab and add/remove boards, the preview disappear?

Waiting for your feedback.

**Comment by sunshin89** [comment]
Yes, once adding more boards than 2x2 the preview vanishes. I have been using your site on my phone since finding it. When I tried on my tablet it never wanted to work properly for me.

**Comment by sunshin89** [comment]
About to retry using chrome on my tablet and see if since the change if it works there

**Comment by maxcleme** [comment]
@sunshin89 , any update ?

**Comment by sunshin89** [comment]
It’s working now with no issues
