### ISSUE TITLE
Excel export enhancements

### ISSUE THREAD

**Issue by lindehell** [maxcleme/beadifier#55]
Love that you have excel export in beta now. I have a few suggestions here as well.

1. Is it possible to have red thick lines as board borders? I work with midi so every 29 row and column. But since you pick what boardtype maybe this could be set for the type used.
2. Thin black/gray lines every five row/columbus. Makes it easier to work with in my opinion. 

I also make the cells square in the way outlined here:
https://superuser.com/questions/165738/how-to-make-cells-perfect-squares-in-excel

This gives you all the advantages of excel in a estethically pleasing and easy to use way.

Love your work on this tool

I always take the excel export and add these manually

**Comment by maxcleme** [comment]
@lindehell 

First of all, thanks for your feedback, I implemented Excel export because some people ask for it but I'm not really a user using it, so thanks for such feedback regarding it.

> Is it possible to have red thick lines as board borders? I work with midi so every 29 row and column. But since you pick what boardtype maybe this could be set for the type used.

Agreed on this, TBH it was in my TODO list but I completely forgot about it. However I dunno if 'red' and 'thick' would be the best possible solution, but as I said, we might have more credit to me regarding excel export.

> Thin black/gray lines every five row/columbus. Makes it easier to work with in my opinion.

Dunno about this, while I understand the idea behind this, why should we create sub-board group in Excel export but not everywhere else ? It would be a good idea, but IMO it would have to be implemented in every exports then.

> I also make the cells square in the way outlined here:
https://superuser.com/questions/165738/how-to-make-cells-perfect-squares-in-excel

I tried to do it when implementing the Excel export, I guess there is few bugs out there (moreover since I do not have Excel and open these with LibreOfficeCalc the results might not be really accurate).

Is there any way for you to post screenshots here in order to have a better idea of your final files ?

**Comment by maxcleme** [comment]
@lindehell 

Regarding square cell, I looked at it again and I'm already doing this kind of tricks.

```typescript
worksheet.properties.defaultRowHeight = 40;
worksheet.properties.defaultColWidth = 40 / 7.025;
```

Everything looks absolutely square here (at least using LibreOffice) : 

![Screenshot from 2020-10-17 13-31-18](https://user-images.githubusercontent.com/7669401/96336040-1b4e3a00-107d-11eb-970a-060ed8e14fbf.png)


Are you sure it is not a default setting in your Excel or whatever ? Would be hard for me to try to fix this without more input TBH.

**Comment by maxcleme** [comment]
@lindehell 

Board border has been added in v1.20.0.

**Comment by maxcleme** [comment]
@lindehell up.
