### ISSUE TITLE
Six new hama colours

### ISSUE THREAD

**Issue by jeppewl** [maxcleme/beadifier#8]
Hama has introduced six new ordinary and opaque colours: 77, 78, 79, 82, 83 and 84 https://www.hama.dk/media/102136/colour-chart_20.pdf

**Comment by maxcleme** [comment]
Awesome! Thanks for feedback, I'm gonna look for rgb references of these and add them asap!

**Comment by jeppewl** [comment]
That sounds good. Are you aware of some good source to get rgb codes? If you wish I can take a high quality photo of them.

**Comment by jeppewl** [comment]
I have made an attempt at sampling the colours in this sheet https://docs.google.com/spreadsheets/d/1Ordv1eQV0HszqxWJf5oM4alch4Q2v5dtiJb-Vui8Rh0/edit?usp=sharing based on this photo I took https://ibb.co/smYnxWv
If look at the older colours, I might not end up with quite the same RGB values as other have, but I am somewhat confident that my values for the six new colours are sufficiently accurate.

**Comment by maxcleme** [comment]
Wow! That's really helpful ! Thanks a lot for taking your time to improve this project.

Here what I'm going to do during the following hours/day : 

1. Update this repo in order to add the 6 new Hama reference based on your work
2. Create a new GitHub repository in order to collect beads color references, defining PR rules etc, it might be a good idea to try to centralized all these Spreadsheets into one repo.
3. If this alternative repository has success and well maintained, I might create some automation for having `beadifier.eremes.xyz` target these and auto-update.

Are you OK with this ?

**Comment by jeppewl** [comment]
Sounds good. Let me know if I can be of any help.

**Comment by maxcleme** [comment]
@jeppewl New colors are now available thanks to you !

**Comment by jeppewl** [comment]
Great!

**Comment by RetrolixusMcD** [comment]
Hey There,

first off, amazing program, i used to use hobby.dk and thought i would be at a loss without it when it closed but your beadifier program is amazing!
colour wise there are the following hama ones missing from the list, is there a way to add them either myself or in general? is it because the RGB cannot be set on them due to being chrome etc?

H15 - TRANSPARENT BLUE
H55 - GLOW IN THE DARK GREEN
H56 - GLOW IN THE DARK RED
H57 - GLOW IN THE DARK BLUE
H61 - GOLD
H62 - SILVER
H63 - BRONZE
H64 - PEARL
H72 - TRANSLUCENT PINK
H73 - TRANSLUCENT AQUA
H74 - TRANSLUCENT AQUA

thanks

Danny McD
